### ISSUE TITLE
'official' omnipay braintree package

### ISSUE THREAD

**Issue by barryvdh** [sproutstudioinc/omnipay-braintree#2]
Hey,

Just to let you know, I started on https://github.com/thephpleague/omnipay-braintree a while back.

Difference with this repo is:
- Braintree SDK `3.1.x`, instead of `~2.0`, so PHP 5.4 is required
- Uses token instead of actual card data (better security)
- Tiny start with the tests
- More fields/parameters

And a few things to note:
- transactionId() is the id of the client. TransactionReference is the id from the gateway. So transactionReference should probably be used, to be consistent with other gateways).

If you feel these issues are not impossible to overcome, I would like to invite you to collaborate on the official omnipay repo: https://github.com/thephpleague/omnipay-braintree

**Comment by Braunson** [comment]
@barryvdh Thanks for the updated, sorry it took so long, updated our readme to point to the official repo. Will jump in to help when I can :+1:
